{
  "formatVersion": "1.1",
  "component": {
    "group": "org.spongepowered",
    "module": "configurate-extra-dfu2",
    "version": "4.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "2.0.24"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-extra-dfu2-4.2.0-SNAPSHOT.jar",
          "url": "configurate-extra-dfu2-4.2.0-SNAPSHOT.jar",
          "size": 7147,
          "sha512": "7505ef35623884ad1cd73f469165db6fe66d5e4f4d3e0b4161e880b373e0c6dc9cda3f7e1c5756189eaf6bcc162a582c4587827516b1b30e2aa6bd53c0ae2680",
          "sha256": "131a4466677c1cdf37880b3e6199c34f659b8b5e14da14ec812c382743de3751",
          "sha1": "c783a3909c6069f0593a60895d73933573184037",
          "md5": "368ddefee151f151e880e76275951e00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "2.0.24"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-extra-dfu2-4.2.0-SNAPSHOT.jar",
          "url": "configurate-extra-dfu2-4.2.0-SNAPSHOT.jar",
          "size": 7147,
          "sha512": "7505ef35623884ad1cd73f469165db6fe66d5e4f4d3e0b4161e880b373e0c6dc9cda3f7e1c5756189eaf6bcc162a582c4587827516b1b30e2aa6bd53c0ae2680",
          "sha256": "131a4466677c1cdf37880b3e6199c34f659b8b5e14da14ec812c382743de3751",
          "sha1": "c783a3909c6069f0593a60895d73933573184037",
          "md5": "368ddefee151f151e880e76275951e00"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "2.0.24"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-extra-dfu2-4.2.0-SNAPSHOT-javadoc.jar",
          "url": "configurate-extra-dfu2-4.2.0-SNAPSHOT-javadoc.jar",
          "size": 84437,
          "sha512": "c3829fdec6e07261945d14f08a9b9db369d30a4a523fe360ef848ba4394bc309fdeceea63ee3e102b32791750552c5736d3dc0819180722c490aafa7008976a8",
          "sha256": "1082d20ab04540b665e6ef5b2f833a6f25db63b336aa528c2d4fbfde40174dbb",
          "sha1": "d3e512e84a620504a9d2ba1dc422da76278a8bf8",
          "md5": "dbccb3cfb0b9c7250cf2cfe647841eb6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configurate-extra-dfu2-4.2.0-SNAPSHOT-sources.jar",
          "url": "configurate-extra-dfu2-4.2.0-SNAPSHOT-sources.jar",
          "size": 4590,
          "sha512": "00b102830f32f79753a20c195970525767df098d621c042ad2f9b7132f153c1fd4dd4cee69c9540f2435a7ae4500668dcf548769d95ebcea41358167e48adce9",
          "sha256": "90b4f593c46614f8b614ea57df23936449a2e5b1552dc2fc622b74d73aeb2f63",
          "sha1": "c0001e335dab2c676871f6388750e719b1ecb98f",
          "md5": "a71b0809d679e4b6f20382d41f308d88"
        }
      ]
    }
  ]
}
