{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nookure.core",
    "module": "NookCore-Messenger",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nookure.core",
          "module": "NookCore-Core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Event",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Player",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "NookCore-Messenger-1.0.0.jar",
          "url": "NookCore-Messenger-1.0.0.jar",
          "size": 2300,
          "sha512": "51462141fa3534f92b5cc8e7234da59a5c3b2c38cbbbdbfab324dec67e73dd24b615a15527e0765229d94e3f06d4934a18267fc2c5e1e2a3c8a316d2df504275",
          "sha256": "9081e2aa173ff7ada8826e781fa8381c5a48f8d6dad9cf0542dac4b8a01d7e1b",
          "sha1": "fe18ff3e82faccf4ff5775851f0a650dda745755",
          "md5": "e71e08c029ea43b360be45ab49d5ad6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nookure.core",
          "module": "NookCore-Core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Event",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Player",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "NookCore-Messenger-1.0.0.jar",
          "url": "NookCore-Messenger-1.0.0.jar",
          "size": 2300,
          "sha512": "51462141fa3534f92b5cc8e7234da59a5c3b2c38cbbbdbfab324dec67e73dd24b615a15527e0765229d94e3f06d4934a18267fc2c5e1e2a3c8a316d2df504275",
          "sha256": "9081e2aa173ff7ada8826e781fa8381c5a48f8d6dad9cf0542dac4b8a01d7e1b",
          "sha1": "fe18ff3e82faccf4ff5775851f0a650dda745755",
          "md5": "e71e08c029ea43b360be45ab49d5ad6f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Messenger-1.0.0-all.jar",
          "url": "NookCore-Messenger-1.0.0-all.jar",
          "size": 18070,
          "sha512": "035c44e155cd30c9f15b2012f670fc0039673ac0f0fdff8bacf654e2a179315c0eed64ef3e8dcb56c910fc90a9e37acb0cbf2f0200931e042ee1bf00935ca4cb",
          "sha256": "b8bc18cae2f24844c94c26324ca0928a58fe4d4ca836098540237a87439eed48",
          "sha1": "153c9478cb74e7ff2c667af8ad2f864892cd4d08",
          "md5": "64459cbd2377d41f58b3dbce64e62672"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Messenger-1.0.0-javadoc.jar",
          "url": "NookCore-Messenger-1.0.0-javadoc.jar",
          "size": 73487,
          "sha512": "26e5e5b36dfd5e82bbcd53331b0e7e700995e14395102c93e8da151c35f38563b0f17c963faa4bec13a108813051d689a3a5c7a9767f4870f076a7bf0560bd7b",
          "sha256": "6158b0b79d48ea684c1de4ca9aa000ea611500cb0f9757c9edec607e24dbc5f2",
          "sha1": "73dee3c102ed1757824bae96e5e2fb5917b0c391",
          "md5": "f88e090f4dec2f1f2222f17db1c42257"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Messenger-1.0.0-sources.jar",
          "url": "NookCore-Messenger-1.0.0-sources.jar",
          "size": 1585,
          "sha512": "df238301e038dfd10251146388c2631cf21bf1e8d6a30e7bc77ba915bf37e0558ea4118d6a6935553e68f34a0dcc5e3c6206d043254f255e789a0b8fb9e87269",
          "sha256": "a2bf89ce57273481c4a439438d5b045a004911fb90434293dd2e06739bf29e42",
          "sha1": "bab1f8755b3aa393376b2000a29e2bbd0e32d7da",
          "md5": "768270e15d57ced3454ee078938527f7"
        }
      ]
    }
  ]
}
