{
  "formatVersion": "1.1",
  "component": {
    "group": "org.spongepowered",
    "module": "configurate-extra-dfu4",
    "version": "4.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "4.0.26"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-extra-dfu4-4.2.0-SNAPSHOT.jar",
          "url": "configurate-extra-dfu4-4.2.0-SNAPSHOT.jar",
          "size": 29162,
          "sha512": "69302f5e98818cdde460376a0784ced52246c6e9586fb820fbfa219e34ef1545eafb29b0ca7b3658adda75209fac4cb2ea875944bf5953605ef6c9022b5e2fa1",
          "sha256": "0799ab732c49cf13d5a812cb1fa03cd5aaac166acc6b3f0deec61ea9c565d4a7",
          "sha1": "12582e577166216e541a08316182fe8820c67d11",
          "md5": "e09494f1ba638ece0eede83f503baac7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "4.0.26"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-extra-dfu4-4.2.0-SNAPSHOT.jar",
          "url": "configurate-extra-dfu4-4.2.0-SNAPSHOT.jar",
          "size": 29162,
          "sha512": "69302f5e98818cdde460376a0784ced52246c6e9586fb820fbfa219e34ef1545eafb29b0ca7b3658adda75209fac4cb2ea875944bf5953605ef6c9022b5e2fa1",
          "sha256": "0799ab732c49cf13d5a812cb1fa03cd5aaac166acc6b3f0deec61ea9c565d4a7",
          "sha1": "12582e577166216e541a08316182fe8820c67d11",
          "md5": "e09494f1ba638ece0eede83f503baac7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "4.0.26"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-extra-dfu4-4.2.0-SNAPSHOT-javadoc.jar",
          "url": "configurate-extra-dfu4-4.2.0-SNAPSHOT-javadoc.jar",
          "size": 145938,
          "sha512": "8ee504c645656a579dbfbf1f17d187512586b1338c19f0624aa6e608b7223a43ccba5e8d5c9cd9e2715ace257d641bd1a797c838c0f619726878e4a314f06e49",
          "sha256": "c90f75438c84770cb3eb68a685c1edd264d2ade25f606d57c76a652fc3200974",
          "sha1": "677eb5efea2a1fd1568c1f8d0cd4e5bd5a7780e1",
          "md5": "ed4616874078d4527a58836815ebb1e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configurate-extra-dfu4-4.2.0-SNAPSHOT-sources.jar",
          "url": "configurate-extra-dfu4-4.2.0-SNAPSHOT-sources.jar",
          "size": 19234,
          "sha512": "cf8765cb97a815dfe5e58e87ebd55880f322ccf8ff7efdf268f408673252a02d684011bbfacf027a35206645a343314a9ace1f64a1dd368239dc9612f5e5e735",
          "sha256": "d388823e86fd90ca1c43e01b22d811c7b27b8fba3654c65167cd4858f6c51808",
          "sha1": "8b74a0288afc7eed5684c09ffb9c1ffbffc01fe4",
          "md5": "5b31b608380541f25b7747f441edc81f"
        }
      ]
    }
  ]
}
