{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nookure.staff",
    "module": "NookureStaff-API",
    "version": "1.5.6-d0acb49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.papermc.paper",
          "module": "paper-api",
          "version": {
            "requires": "1.21.4-R0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.5-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "redis.clients",
          "module": "jedis",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ebean",
          "module": "ebean",
          "version": {
            "requires": "15.1.0"
          }
        },
        {
          "group": "me.clip",
          "module": "placeholderapi",
          "version": {
            "requires": "2.11.6"
          }
        }
      ],
      "files": [
        {
          "name": "NookureStaff-API-1.5.6-d0acb49.jar",
          "url": "NookureStaff-API-1.5.6-d0acb49.jar",
          "size": 195698,
          "sha512": "3ca54a4c71aed79ba3cb8f54221ee61782d8cc133e73ea95beeb47175241fa2d56b376694af21006aa73c76f7d99bc34361e6500fe957e4b7e415a25cc17de9f",
          "sha256": "b96b2ffde326a5d332293bb61bd5a9a3a052410e3a899ab9f852d414dd315d0d",
          "sha1": "baee5197db202302f0b6678a43356f1db84efaf9",
          "md5": "b60fa39428a0367a568fb4ca3e009aa6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0-YAML-COMMENTED-SNAPSHOT"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "NookureStaff-API-1.5.6-d0acb49.jar",
          "url": "NookureStaff-API-1.5.6-d0acb49.jar",
          "size": 195698,
          "sha512": "3ca54a4c71aed79ba3cb8f54221ee61782d8cc133e73ea95beeb47175241fa2d56b376694af21006aa73c76f7d99bc34361e6500fe957e4b7e415a25cc17de9f",
          "sha256": "b96b2ffde326a5d332293bb61bd5a9a3a052410e3a899ab9f852d414dd315d0d",
          "sha1": "baee5197db202302f0b6678a43356f1db84efaf9",
          "md5": "b60fa39428a0367a568fb4ca3e009aa6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.5.6-d0acb49-all.jar",
          "url": "NookureStaff-API-1.5.6-d0acb49-all.jar",
          "size": 971883,
          "sha512": "6a22094e1fbe2a65e01653fe333dc5f9a4ccd3dd4ffa45c907758874cdf51f571e7434891beb6f18bafb7a27c6f056f497d883f259133dbe440ffc1158e953b4",
          "sha256": "852cdd23b219e8506697e9bd63d0897c5e82617a2452a2472d6c4ef9d1ae0d05",
          "sha1": "e077429108e14234a0345580ed098031be00e56f",
          "md5": "ab36ea3d3a9aa91d270e18576ee6dd1d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.5.6-d0acb49-javadoc.jar",
          "url": "NookureStaff-API-1.5.6-d0acb49-javadoc.jar",
          "size": 738403,
          "sha512": "3d95acaed297d422fb2d6c9737ed4c3c184cc9f2d23eeb882f0eaab133ba7820af8dc25077ab05819f558a124e4062aa0f012b6dba643723b3b6a6b51a0ee558",
          "sha256": "9e6b4cb2db6076f0a3937610cc9dfe91a985c470a75282d4df9b1be19f041351",
          "sha1": "54cd79860d67334450ef7f7c6a0d24e7fde06c88",
          "md5": "f97be695f2e6c4e4c08f4ed9dcedb515"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.5.6-d0acb49-sources.jar",
          "url": "NookureStaff-API-1.5.6-d0acb49-sources.jar",
          "size": 106420,
          "sha512": "f158f8624682a0225a3ba5eff06737d63c08f98dd75901861f88b5ed3aa8a4bab1aa65341933f234936887c8a6905f5f0c35270fc2547497ef6fc34e6652f15e",
          "sha256": "19fddd205f61a5bf26793ecea5a9ad41cc99700a315ca56084d5df9d59ddb1ba",
          "sha1": "2012edc36c9af4dfb7b0708b6e8c240b1b0a401b",
          "md5": "ffd91badc797a840c5f535cc3117c8f9"
        }
      ]
    }
  ]
}
