{
  "formatVersion": "1.1",
  "component": {
    "group": "org.spongepowered",
    "module": "configurate-core",
    "version": "4.2.0-YAML-COMMENTED-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.leangen.geantyref",
          "module": "geantyref",
          "version": {
            "requires": "1.3.14"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.42.0"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-core-4.2.0-YAML-COMMENTED-SNAPSHOT.jar",
          "url": "configurate-core-4.2.0-YAML-COMMENTED-SNAPSHOT.jar",
          "size": 341408,
          "sha512": "fe824ea3edd383565a6acc496cabee765b3111a001d6b2f843006cf51a88bb1da9c3777a226e44e1a998f451d2a63baaf8f023fa5195f36bbddc545d196b8e06",
          "sha256": "dc573e2af6d1e1ce3f25fdd194e8ead4711d7fe9bb6edee4a37ca99899739b49",
          "sha1": "f3a51c738aeedbe1c66c033ba38819be92d5cfaf",
          "md5": "32c1a7040ca24265a254f1a833784eb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.leangen.geantyref",
          "module": "geantyref",
          "version": {
            "requires": "1.3.14"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-core-4.2.0-YAML-COMMENTED-SNAPSHOT.jar",
          "url": "configurate-core-4.2.0-YAML-COMMENTED-SNAPSHOT.jar",
          "size": 341408,
          "sha512": "fe824ea3edd383565a6acc496cabee765b3111a001d6b2f843006cf51a88bb1da9c3777a226e44e1a998f451d2a63baaf8f023fa5195f36bbddc545d196b8e06",
          "sha256": "dc573e2af6d1e1ce3f25fdd194e8ead4711d7fe9bb6edee4a37ca99899739b49",
          "sha1": "f3a51c738aeedbe1c66c033ba38819be92d5cfaf",
          "md5": "32c1a7040ca24265a254f1a833784eb7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.leangen.geantyref",
          "module": "geantyref",
          "version": {
            "requires": "1.3.14"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.42.0"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-core-4.2.0-YAML-COMMENTED-SNAPSHOT-javadoc.jar",
          "url": "configurate-core-4.2.0-YAML-COMMENTED-SNAPSHOT-javadoc.jar",
          "size": 862674,
          "sha512": "9681827c5645d750278806e0c09539facefb3f0f3c7d43cf062f4293154d95776498d6e2736fa6e027726092040f771fb4579a171eff4fcbb1007dc7ba3a0733",
          "sha256": "ee85a491d066b6f8327304b40c2ae9614e4f3349a8e8871ae007d6e546b16669",
          "sha1": "cc118416a170139e2bc4350c8ac2bf0bb6ae3beb",
          "md5": "e983b96a39658b66465127d9b07ee0df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configurate-core-4.2.0-YAML-COMMENTED-SNAPSHOT-sources.jar",
          "url": "configurate-core-4.2.0-YAML-COMMENTED-SNAPSHOT-sources.jar",
          "size": 225095,
          "sha512": "4e56499b179ca77fe9f832bd881f6247b9c694f8e170ec57ece545d28c45e94c584bb28146d004b2197b7a2a2deec6f537e56228cb2e8df3faf71761761129aa",
          "sha256": "1cdc9b6b3a37975e168acdbaaf596ab283ea44540615442b9e75318d3d28c95a",
          "sha1": "f158ef838dee27322da71ed27b31dbf096b2ae52",
          "md5": "971f90d6ee11a631e46aa5f161b062dd"
        }
      ]
    }
  ]
}
