{
  "formatVersion": "1.1",
  "component": {
    "group": "org.spongepowered",
    "module": "configurate-yaml",
    "version": "4.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-yaml-4.2.0-SNAPSHOT.jar",
          "url": "configurate-yaml-4.2.0-SNAPSHOT.jar",
          "size": 359454,
          "sha512": "b7d94566f64a826b9aa9ae3042352d8dc603ed4ecf3fe8c3f5d5c98bd4da8559112bc668cd9e417c146f52e7888cefed3e719271ef2e21e757609fcc38695f3f",
          "sha256": "0f3569991129e51c7408d0951ced5ab0f2f42dc9dd8cdc6c655519fe826a022c",
          "sha1": "789c00b9dc277bb8f27ca29ddafd158df89c1400",
          "md5": "9f0cfab7c8cd77a26144bc4e07510c9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-yaml-4.2.0-SNAPSHOT.jar",
          "url": "configurate-yaml-4.2.0-SNAPSHOT.jar",
          "size": 359454,
          "sha512": "b7d94566f64a826b9aa9ae3042352d8dc603ed4ecf3fe8c3f5d5c98bd4da8559112bc668cd9e417c146f52e7888cefed3e719271ef2e21e757609fcc38695f3f",
          "sha256": "0f3569991129e51c7408d0951ced5ab0f2f42dc9dd8cdc6c655519fe826a022c",
          "sha1": "789c00b9dc277bb8f27ca29ddafd158df89c1400",
          "md5": "9f0cfab7c8cd77a26144bc4e07510c9e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0-SNAPSHOT"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-yaml-4.2.0-SNAPSHOT-javadoc.jar",
          "url": "configurate-yaml-4.2.0-SNAPSHOT-javadoc.jar",
          "size": 109112,
          "sha512": "6d3badc50b1e6fb445b9460d05f48ed615b41ac509cee413b47e255c074ea1f1aa71a3065fe1f2544efa54447e2ffe7d5f279355ecb4220ae1a299bb0b6ae859",
          "sha256": "272e0ad2e2ac26d9cb2948db4b926923d4ea15d7daf240ec0c4deb8eb75515cb",
          "sha1": "d673896ee377080358eaa6decdafc8644603f2d5",
          "md5": "834ea09b33b3b8af92726fbf3edd9e79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configurate-yaml-4.2.0-SNAPSHOT-sources.jar",
          "url": "configurate-yaml-4.2.0-SNAPSHOT-sources.jar",
          "size": 12300,
          "sha512": "0b1605a9ac2b86dfbcbfbe4966e55347f7a04d5a8b7a1b4dd4e946c316a0a559b9fbcfe321c982d70a6d824beb6506bd184d4d3542ce1ae6e1407fde3b716567",
          "sha256": "bb11182cac2fd3e36267c6740038d347c78ebdb93a417abb425a902c985e9550",
          "sha1": "9ecb265464fa02afcd95af0eb67b90c66f2946c0",
          "md5": "eecde262826aa89b850f39c5e294b884"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configurate-yaml-4.2.0-SNAPSHOT.jar",
          "url": "configurate-yaml-4.2.0-SNAPSHOT.jar",
          "size": 359454,
          "sha512": "b7d94566f64a826b9aa9ae3042352d8dc603ed4ecf3fe8c3f5d5c98bd4da8559112bc668cd9e417c146f52e7888cefed3e719271ef2e21e757609fcc38695f3f",
          "sha256": "0f3569991129e51c7408d0951ced5ab0f2f42dc9dd8cdc6c655519fe826a022c",
          "sha1": "789c00b9dc277bb8f27ca29ddafd158df89c1400",
          "md5": "9f0cfab7c8cd77a26144bc4e07510c9e"
        }
      ]
    }
  ]
}
