{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nookure.staff",
    "module": "NookureStaff-API",
    "version": "1.5.6-347a576",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.papermc.paper",
          "module": "paper-api",
          "version": {
            "requires": "1.21.4-R0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.5-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "redis.clients",
          "module": "jedis",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ebean",
          "module": "ebean",
          "version": {
            "requires": "15.1.0"
          }
        },
        {
          "group": "me.clip",
          "module": "placeholderapi",
          "version": {
            "requires": "2.11.6"
          }
        }
      ],
      "files": [
        {
          "name": "NookureStaff-API-1.5.6-347a576.jar",
          "url": "NookureStaff-API-1.5.6-347a576.jar",
          "size": 195697,
          "sha512": "e5383192a80400e39376ac184e514cee8ce9d36f53f5fc95362da58a42e1e9be5fde37461bc50a27f9f180c4d456c662182d79269939cf9a96571488db285170",
          "sha256": "3a5569b3c0a3462976605a42e267bb78790a1f537beb70b37c3cf2e3577ca7c7",
          "sha1": "831b7f1d7dc882ad8ddd0e2f071f68b46e762830",
          "md5": "f750df97a1e04e05bb01f60aa6050486"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0-YAML-COMMENTED-SNAPSHOT"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "NookureStaff-API-1.5.6-347a576.jar",
          "url": "NookureStaff-API-1.5.6-347a576.jar",
          "size": 195697,
          "sha512": "e5383192a80400e39376ac184e514cee8ce9d36f53f5fc95362da58a42e1e9be5fde37461bc50a27f9f180c4d456c662182d79269939cf9a96571488db285170",
          "sha256": "3a5569b3c0a3462976605a42e267bb78790a1f537beb70b37c3cf2e3577ca7c7",
          "sha1": "831b7f1d7dc882ad8ddd0e2f071f68b46e762830",
          "md5": "f750df97a1e04e05bb01f60aa6050486"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.5.6-347a576-all.jar",
          "url": "NookureStaff-API-1.5.6-347a576-all.jar",
          "size": 971882,
          "sha512": "769ae7ae430d6ec27ecad412009effd9f077cb8e6199765934282e43ddb7658c82d2614e79404c129a1f562f1f70bbbe55f421d3b705b7487ad1547b1411032a",
          "sha256": "4d1a2e99d7a3cee3ac26a1a22e13e39d83baecc08a58b8d6bf6a1779dfacdd44",
          "sha1": "64d88d8acd2950b8518d32cf156c03dca60ff965",
          "md5": "b9b0147f7e6288b1e24d44235f114b6a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.5.6-347a576-javadoc.jar",
          "url": "NookureStaff-API-1.5.6-347a576-javadoc.jar",
          "size": 738405,
          "sha512": "7ef69353cb9c26a353fbf551fef7751b4a8e672ff9d1dedd1d45901504744939824b2af403138c5b4e21b1d9432e2c573bcbfde916cf88b3bdbec64d0f8edd94",
          "sha256": "7d15e505aac0af934e9dc299ee6d7927316e44c6afd4599d5519479ac8ac2e09",
          "sha1": "75b3e8d7a6312fa46fcb632ace42a6e05ffcc550",
          "md5": "59fceb5913ea8894e55f7706e08fb011"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.5.6-347a576-sources.jar",
          "url": "NookureStaff-API-1.5.6-347a576-sources.jar",
          "size": 106419,
          "sha512": "6902c2f450e78a3fa5bc890f9119612fc4b6021a11f19722ad9eed91a27d3e8c66a6035bfacc98424a9e6fc73685508e236dcaf3f8b905dc59baa08062c5937d",
          "sha256": "8cbd7a56cf2a976081ab9b537a52699d6c96784cf1d4360ce635546a1aee9b68",
          "sha1": "7a3f840f18403be874c1be255f43af4e6059210a",
          "md5": "4dc51e9995cc648f7d9971f43636fd63"
        }
      ]
    }
  ]
}
