{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nookure.staff",
    "module": "NookureStaff-API",
    "version": "1.2.1-b5d4ea2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.papermc.paper",
          "module": "paper-api",
          "version": {
            "requires": "1.20.4-R0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "redis.clients",
          "module": "jedis",
          "version": {
            "requires": "4.4.0-m2"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.1.8"
          }
        },
        {
          "group": "io.ebean",
          "module": "ebean",
          "version": {
            "requires": "15.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "NookureStaff-API-1.2.1-b5d4ea2.jar",
          "url": "NookureStaff-API-1.2.1-b5d4ea2.jar",
          "size": 117453,
          "sha512": "6a77cdd286ea1c833752b0be6e2fddc341077655f4ad33a630baf964bc7d08bfd238ed2ef9e238ff2b42db6266bb9a18d49625974aee3b1da7e2a864f8363b94",
          "sha256": "b3df98bc7beafaed2a848e3721242124f25b4171e75fca1990a590f3141b4f50",
          "sha1": "2de1da11480ff7721045fa009dc01563ceb3a7a0",
          "md5": "d060b83e966aee033100304dd979b7a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0-YAML-COMMENTED-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "NookureStaff-API-1.2.1-b5d4ea2.jar",
          "url": "NookureStaff-API-1.2.1-b5d4ea2.jar",
          "size": 117453,
          "sha512": "6a77cdd286ea1c833752b0be6e2fddc341077655f4ad33a630baf964bc7d08bfd238ed2ef9e238ff2b42db6266bb9a18d49625974aee3b1da7e2a864f8363b94",
          "sha256": "b3df98bc7beafaed2a848e3721242124f25b4171e75fca1990a590f3141b4f50",
          "sha1": "2de1da11480ff7721045fa009dc01563ceb3a7a0",
          "md5": "d060b83e966aee033100304dd979b7a6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.2.1-b5d4ea2-all.jar",
          "url": "NookureStaff-API-1.2.1-b5d4ea2-all.jar",
          "size": 886632,
          "sha512": "adadb8f78432bf891f9f674c7366fe1762992def4d24e532e5bf34c313bb1e668ccef9ba5c5be8ceb54d417fc7583d738ed645e337ee034b2784cf964ce52d80",
          "sha256": "90dac0e6b738116bf189c8275db3ed07ce6120d4ef54409ae6fdbd7e849e4a84",
          "sha1": "88b2c8b8ecbd639c2a008bbb42a029da065ae450",
          "md5": "2029fb64e5a83fee389e25a40e8ecde2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.2.1-b5d4ea2-javadoc.jar",
          "url": "NookureStaff-API-1.2.1-b5d4ea2-javadoc.jar",
          "size": 490225,
          "sha512": "764685a77647eb402f2fa6eb0a9e445e6eaf8b4e78ffad5574c6b4b086d18f564ff85fcd06f51c4707ea61ef4b97cd2d1bcb71ba687633d1f2a3f440681053a6",
          "sha256": "1aa847c42680697028a080018ceec944af34aafcf3588e0e26f8012a6aa30cc6",
          "sha1": "1be0c56819c9c366e0212ed1bbd38ca0fb9bec10",
          "md5": "a62761ef8d742082729188f082ceb416"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.2.1-b5d4ea2-sources.jar",
          "url": "NookureStaff-API-1.2.1-b5d4ea2-sources.jar",
          "size": 70545,
          "sha512": "3e66ce8430a9187a15b759c72a9e47f78ee4a96a42bc309cbb83118cb9c81a0cc300e5e168896eb8b78f70107d8f837ddcc0e9ffb1c7afb8b25db05f5ceda2dc",
          "sha256": "26cab39adc503cc74a578c00c7e235cc8d25f1b08921df257f50b2bcfc03754b",
          "sha1": "2acda35e594cb243003dccec7be08dd7e7f99f6b",
          "md5": "afd97d495f995d7ff38341a5ab5a1d92"
        }
      ]
    }
  ]
}
