{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nookure.staff",
    "module": "NookureStaff-API",
    "version": "1.2.1-ab4e542",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.papermc.paper",
          "module": "paper-api",
          "version": {
            "requires": "1.20.4-R0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "redis.clients",
          "module": "jedis",
          "version": {
            "requires": "4.4.0-m2"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.1.8"
          }
        },
        {
          "group": "io.ebean",
          "module": "ebean",
          "version": {
            "requires": "15.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "NookureStaff-API-1.2.1-ab4e542.jar",
          "url": "NookureStaff-API-1.2.1-ab4e542.jar",
          "size": 138112,
          "sha512": "ed810ff4b026dc12e092066ca2759ab98270f373a1b925a8c09649f9814b1c188d42d095682b0af5ac5c6236dd2ae62c3b7178c242262079c237e24e450442af",
          "sha256": "d7a652bd2cd1e4b5c4d4a4f0feefffd62763ad27862192ef81b8541e5b504c01",
          "sha1": "7fd69f1f03fbf4a3d36c6b7229416bfb147cc54f",
          "md5": "68a2e84dbebe1e97141b42885cde27e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0-YAML-COMMENTED-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "NookureStaff-API-1.2.1-ab4e542.jar",
          "url": "NookureStaff-API-1.2.1-ab4e542.jar",
          "size": 138112,
          "sha512": "ed810ff4b026dc12e092066ca2759ab98270f373a1b925a8c09649f9814b1c188d42d095682b0af5ac5c6236dd2ae62c3b7178c242262079c237e24e450442af",
          "sha256": "d7a652bd2cd1e4b5c4d4a4f0feefffd62763ad27862192ef81b8541e5b504c01",
          "sha1": "7fd69f1f03fbf4a3d36c6b7229416bfb147cc54f",
          "md5": "68a2e84dbebe1e97141b42885cde27e3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.2.1-ab4e542-all.jar",
          "url": "NookureStaff-API-1.2.1-ab4e542-all.jar",
          "size": 907291,
          "sha512": "4d9f629d69ad11101c0b4bf5b87a2b260e33d0d07852f1ce0fb47468d0d95f4e011d7a4a196ce22ce20c0f81e15d5ab305682ef51a01b2b1e7533239d4ee7526",
          "sha256": "66f9f718bfeb9d8a9df6fbfdccab8d6178ac9222ba81adb376effd148871ff9c",
          "sha1": "034a49831896ff44ec8b61b2a4aae935846bf182",
          "md5": "cbdedd7b4f4764a581fa53307fc1247e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.2.1-ab4e542-javadoc.jar",
          "url": "NookureStaff-API-1.2.1-ab4e542-javadoc.jar",
          "size": 542338,
          "sha512": "679ba3d6e619bf30ee90a0c36c156ef3c4b2656f4bc99fcb9641632fa4ac70b16cb48d920b3199e65735894b4404bc9d053ca3e81c2d06657cd9557333ad3c0a",
          "sha256": "f709fa29d750c454deb99e9aa288019dd58c4f8a205c41ccc219c1dd42036826",
          "sha1": "e6d32c3bbf0d12c02961c44f883b576da3068e01",
          "md5": "aa7c8098193c6e05f406d7ebf2ab59cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookureStaff-API-1.2.1-ab4e542-sources.jar",
          "url": "NookureStaff-API-1.2.1-ab4e542-sources.jar",
          "size": 79541,
          "sha512": "0c3fffffa55fd3e5b0680a160d12268347cabe4b92f86d4f5214352b59971c4f24f3dd829504ba30c7cdbe14586df00c95fa7e620df290cf22fecf6a0bb7ef8c",
          "sha256": "fed7ac9b8917ecac2b9a3ca6b020f4d063718d31d611c61ab3d740d16a5b7adf",
          "sha1": "5b2fb7fe44e3a00acc625d8f09e60bf50a79d082",
          "md5": "7becb35ad455ced480850465415d080b"
        }
      ]
    }
  ]
}
