{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nookure.core",
    "module": "NookCore-Command",
    "version": "1.1.0-d89740c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nookure.core",
          "module": "NookCore-Player",
          "version": {
            "requires": "1.1.0-d89740c"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Core",
          "version": {
            "requires": "1.1.0-d89740c"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Logger",
          "version": {
            "requires": "1.1.0-d89740c"
          }
        }
      ],
      "files": [
        {
          "name": "NookCore-Command-1.1.0-d89740c.jar",
          "url": "NookCore-Command-1.1.0-d89740c.jar",
          "size": 16010,
          "sha512": "e745ce2b68ce2920e5d0643c3bb90bbd4cede09ca2fef32ade7a7ad74b63912942e5a652d57be1c8973cb0e34b85ac1502df6fafe279578a965830d74b51d826",
          "sha256": "f285b251febd94752a48a38540f9264b462321d9edfd0aa78d7da4a3bcbba207",
          "sha1": "7bc0cedc82aceaf4ad3eb48150115d9efc50736d",
          "md5": "ccf13c880d68c740f285d5127d83bb88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nookure.core",
          "module": "NookCore-Player",
          "version": {
            "requires": "1.1.0-d89740c"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Core",
          "version": {
            "requires": "1.1.0-d89740c"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Logger",
          "version": {
            "requires": "1.1.0-d89740c"
          }
        }
      ],
      "files": [
        {
          "name": "NookCore-Command-1.1.0-d89740c.jar",
          "url": "NookCore-Command-1.1.0-d89740c.jar",
          "size": 16010,
          "sha512": "e745ce2b68ce2920e5d0643c3bb90bbd4cede09ca2fef32ade7a7ad74b63912942e5a652d57be1c8973cb0e34b85ac1502df6fafe279578a965830d74b51d826",
          "sha256": "f285b251febd94752a48a38540f9264b462321d9edfd0aa78d7da4a3bcbba207",
          "sha1": "7bc0cedc82aceaf4ad3eb48150115d9efc50736d",
          "md5": "ccf13c880d68c740f285d5127d83bb88"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Command-1.1.0-d89740c-all.jar",
          "url": "NookCore-Command-1.1.0-d89740c-all.jar",
          "size": 25359,
          "sha512": "4d2b526d7fbd9ff8a0b219e9a02fe85ed8fb168309f50c683be24c6cc4d56f8b7951b145fc411c8653d6cf03cc7184bf4bda4a84b3eb4974179f370b4bf3cb14",
          "sha256": "c568acf468555c556995895666801838f9ac9dddbb96e1fc0ba7c75f9f1c1e9a",
          "sha1": "6b0febc284e4a7394f499d0e78ce41397700e350",
          "md5": "d96a9de25632f206ab7c5242429a6374"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Command-1.1.0-d89740c-javadoc.jar",
          "url": "NookCore-Command-1.1.0-d89740c-javadoc.jar",
          "size": 119792,
          "sha512": "f0470a920e52df85f85b4a3cc80f5ad2bfed20c328ffcc9416bbad50989d7b4f516e1d2e23aa4112f0364bded3ac385fe53b84b5460628804b96094846696493",
          "sha256": "5f6e5a9764abf89a3519c288fed5e5ca7ebaacd9399ff93aeda48e20b5322b09",
          "sha1": "ceb338845893ad36406b97f8f019b68d3b7cf173",
          "md5": "1ad8e58f06324f1cbab4a16ff3126a47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Command-1.1.0-d89740c-sources.jar",
          "url": "NookCore-Command-1.1.0-d89740c-sources.jar",
          "size": 8582,
          "sha512": "4595ad1c384aa5e15df76d55b20af9c9ab626d9f171fa94d178534a28b888d40cd9cf03b5d674af9fe3c5714ab1c37fa6d033dfb29f195f922d356ccf24bd50d",
          "sha256": "ebbf092ed4eac8d7fff26efa2ab165ca5e18516774c6d38c25fba5c79eb693d5",
          "sha1": "a4fb509cc99b9b233bbcdce56fa90d0ac2e20c15",
          "md5": "6d81d1bba495169f7cdb776d99503c69"
        }
      ]
    }
  ]
}
