{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nookure.core",
    "module": "NookCore-Database",
    "version": "1.1.0-6de8391",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.ebean",
          "module": "ebean",
          "version": {
            "requires": "15.1.0"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Logger",
          "version": {
            "requires": "1.1.0-6de8391"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Core",
          "version": {
            "requires": "1.1.0-6de8391"
          }
        }
      ],
      "files": [
        {
          "name": "NookCore-Database-1.1.0-6de8391.jar",
          "url": "NookCore-Database-1.1.0-6de8391.jar",
          "size": 9011,
          "sha512": "75c653fa541f2b8fd5d459a95f688df26a5332fafabb378a17fba8f1a22f72fd90779c9f0c94a21be1bb168661079bf16d4d517431357ba1b0151e7f906cb284",
          "sha256": "331daec3b8fed0e4113465336d25ad9eaa1aa7f8457a31c4c7b103db20e58ada",
          "sha1": "e26114eb5d944e587ecfbbfbfbf6e907adf53099",
          "md5": "d90499094f7184713b347e7fdce5298e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "io.ebean",
          "module": "ebean",
          "version": {
            "requires": "15.1.0"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Logger",
          "version": {
            "requires": "1.1.0-6de8391"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Core",
          "version": {
            "requires": "1.1.0-6de8391"
          }
        }
      ],
      "files": [
        {
          "name": "NookCore-Database-1.1.0-6de8391.jar",
          "url": "NookCore-Database-1.1.0-6de8391.jar",
          "size": 9011,
          "sha512": "75c653fa541f2b8fd5d459a95f688df26a5332fafabb378a17fba8f1a22f72fd90779c9f0c94a21be1bb168661079bf16d4d517431357ba1b0151e7f906cb284",
          "sha256": "331daec3b8fed0e4113465336d25ad9eaa1aa7f8457a31c4c7b103db20e58ada",
          "sha1": "e26114eb5d944e587ecfbbfbfbf6e907adf53099",
          "md5": "d90499094f7184713b347e7fdce5298e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Database-1.1.0-6de8391-all.jar",
          "url": "NookCore-Database-1.1.0-6de8391-all.jar",
          "size": 5889202,
          "sha512": "7452fcddf8e253cbd3144d53c9d72d12854f05cd073e7fc2bda4c60481629d4e35429a8d704dea24ab2f54e3457cce73a6117549ca2aae2f68293633114463d3",
          "sha256": "e202e56a58a5e49a35d8e660bbec446d36c4a7c135e6d29a10e46477f75b0805",
          "sha1": "bfc8b099a6524ed75235c55421d647d287fed887",
          "md5": "49cd865dab85c5de4e4e297801c1d611"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Database-1.1.0-6de8391-javadoc.jar",
          "url": "NookCore-Database-1.1.0-6de8391-javadoc.jar",
          "size": 103732,
          "sha512": "b2f4701b3911f8d218a73380c52e2ce8d8137eef2108889c0d9c8715a46cefe26dcd9f5a2e0befeab41c728f4e119203c01346ece841a3c3d764d88720f16274",
          "sha256": "0719bc2dc2f06e4245ea68dcb0b6fa3c1fecd78e9f49a69e2ebedcccfe2d46d4",
          "sha1": "797eacf761030d82b4c9faa1029ee66b73b734ee",
          "md5": "c13ddc339552d4a318fb92bd879516c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Database-1.1.0-6de8391-sources.jar",
          "url": "NookCore-Database-1.1.0-6de8391-sources.jar",
          "size": 5684,
          "sha512": "349bbf306b045e351b2e2bca1b1e9b2526ce05e88e8e723aaa7e1dbd4a74dcc27ec3d25e9d517090ed0b0ae4883dec93fa0615ac2d2af5c54f897c7f6719e504",
          "sha256": "9040d12598b1ae5276342ce9434e815720075485e36737f3e0ba5155e98ed344",
          "sha1": "71245abe648e18e003b64013301a3de9260c594f",
          "md5": "5e2302a762c9e1a738a7d81ebb714206"
        }
      ]
    }
  ]
}
