{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nookure.core",
    "module": "NookCore-Logger",
    "version": "1.1.0-e8df898",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "NookCore-Logger-1.1.0-e8df898.jar",
          "url": "NookCore-Logger-1.1.0-e8df898.jar",
          "size": 4092,
          "sha512": "476ca8bb66c693389d59f609d3a732a402dd99e37e06957a9182cbcdd6c307446f205789fddaac4c0c885696fb5f872a71067e21b36612915c1698bf7493c773",
          "sha256": "c84220716d0d04cc667538bb88be9ef20e256b421e72081fb51eef17691ca241",
          "sha1": "a7f0afff10030a9d8834352b1b849f6d7ced04fd",
          "md5": "e109ee3da18414c29cf7a3d5d7fd6258"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Logger-1.1.0-e8df898.jar",
          "url": "NookCore-Logger-1.1.0-e8df898.jar",
          "size": 4092,
          "sha512": "476ca8bb66c693389d59f609d3a732a402dd99e37e06957a9182cbcdd6c307446f205789fddaac4c0c885696fb5f872a71067e21b36612915c1698bf7493c773",
          "sha256": "c84220716d0d04cc667538bb88be9ef20e256b421e72081fb51eef17691ca241",
          "sha1": "a7f0afff10030a9d8834352b1b849f6d7ced04fd",
          "md5": "e109ee3da18414c29cf7a3d5d7fd6258"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Logger-1.1.0-e8df898-all.jar",
          "url": "NookCore-Logger-1.1.0-e8df898-all.jar",
          "size": 4092,
          "sha512": "12b63e92097848ba8558c9e9dfc0f2accb6005929c1a5eb022f5391c5347832cd223556baff655ddc02b67eb34c4b4b0248a82b34717e07d33ed5651a83a0ecc",
          "sha256": "341496df343eda53efe3d56c7c52da6dcfe2807a180722d544b0e11793805d6e",
          "sha1": "11c0c63fd2a1fadf3e78abe13bc20b0ca971ae89",
          "md5": "dc36c722d28edbda08947d0aa0ffedf1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Logger-1.1.0-e8df898-javadoc.jar",
          "url": "NookCore-Logger-1.1.0-e8df898-javadoc.jar",
          "size": 91611,
          "sha512": "11b2db18c5d16682ee732bac4771b78f81ca711c781a0f3cb19029d79b9e7fc4b0100c0b8677fb1c62ae8c275ddd41861c608c8193690f824a387ae833e391e2",
          "sha256": "76f2cb5bf4450aa23a373fd457ef5085897773045cea2298869e2721cafa4c83",
          "sha1": "3dcd08048a1883ee98a75c11797ee3e23a0c171a",
          "md5": "5184ac6b7d0f66e1399f16d50ddbb0f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Logger-1.1.0-e8df898-sources.jar",
          "url": "NookCore-Logger-1.1.0-e8df898-sources.jar",
          "size": 2902,
          "sha512": "c0ee3fab0da55e1aeb4c711b5a9f87ceecdf92a631e0b029af7d87b5fbc535988500c13527695ddd3b43bcf394ccb057c412b8e7be3365d861fdc48e53f9b9e6",
          "sha256": "77c42b00594a924dad2e2c712ccd14f4a608cb018e1ac1a7a80473725d5d1fce",
          "sha1": "c8bb5a880f5d6a047f56b479fd4c18611da4488f",
          "md5": "e79f69740a4f7e950af9eba760beed83"
        }
      ]
    }
  ]
}
