{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nookure.core",
    "module": "NookCore-Event",
    "version": "1.0.0-4f4ee44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nookure.core",
          "module": "NookCore-Logger",
          "version": {
            "requires": "1.0.0-4f4ee44"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Core",
          "version": {
            "requires": "1.0.0-4f4ee44"
          }
        }
      ],
      "files": [
        {
          "name": "NookCore-Event-1.0.0-4f4ee44.jar",
          "url": "NookCore-Event-1.0.0-4f4ee44.jar",
          "size": 8340,
          "sha512": "026d1bea1a7287c2f76bde0ba1bf777b0229d2576413729a30fed45127a18b24929c3859447699bdaa032e41f2d8a4d98103786bd15ccedb00d85e9deab8ddc8",
          "sha256": "41ec66a9b78472bc50fc8d2af5ff6aa820fec8f8824b8232eb686190890e8056",
          "sha1": "673a676efc71a1b9d89da2144161eca0896a13fe",
          "md5": "522bb0469e04c6c7d7f84f6c3c030c27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nookure.core",
          "module": "NookCore-Logger",
          "version": {
            "requires": "1.0.0-4f4ee44"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Core",
          "version": {
            "requires": "1.0.0-4f4ee44"
          }
        }
      ],
      "files": [
        {
          "name": "NookCore-Event-1.0.0-4f4ee44.jar",
          "url": "NookCore-Event-1.0.0-4f4ee44.jar",
          "size": 8340,
          "sha512": "026d1bea1a7287c2f76bde0ba1bf777b0229d2576413729a30fed45127a18b24929c3859447699bdaa032e41f2d8a4d98103786bd15ccedb00d85e9deab8ddc8",
          "sha256": "41ec66a9b78472bc50fc8d2af5ff6aa820fec8f8824b8232eb686190890e8056",
          "sha1": "673a676efc71a1b9d89da2144161eca0896a13fe",
          "md5": "522bb0469e04c6c7d7f84f6c3c030c27"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Event-1.0.0-4f4ee44-all.jar",
          "url": "NookCore-Event-1.0.0-4f4ee44-all.jar",
          "size": 4013862,
          "sha512": "a9389e0cf61787916f3f28cc0e01fc80d6d66f48fc5fe04946b6b92b982a01fa65dfe8377a8ef4d499b3b3538658521217bad731b14aaa4bc8543d0e057e5392",
          "sha256": "b8afc7b2a9909eee1158dd222fc48f091963182b16207b57bb0cd3b2ee8076a0",
          "sha1": "4b0fc1f7403294ba0b37e0e92fdd647cefbae91d",
          "md5": "ad33aafa84565f3c5087a8acc1663364"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Event-1.0.0-4f4ee44-javadoc.jar",
          "url": "NookCore-Event-1.0.0-4f4ee44-javadoc.jar",
          "size": 101794,
          "sha512": "b52874f5dce12a55e8c17cb347f12401cbb2f7b811ec57075ba779a28cd96f5bddececba3b56c63dea81a49d4f278c8be7ba37e7115ed75757ea3054dfab22cc",
          "sha256": "6eca1eba1367e33fac9e9cd12fc7ac1b25597f76aab822cf9dd415bdb426d676",
          "sha1": "c660cc898e91cdad71b1c6e43ff81679d19c8538",
          "md5": "74881a2e1068b420c5d60b7b431a208d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Event-1.0.0-4f4ee44-sources.jar",
          "url": "NookCore-Event-1.0.0-4f4ee44-sources.jar",
          "size": 4762,
          "sha512": "03dff8676ac4bbc407d0541bbe44da825fbaa6b1a14838c7415e182d74182fc1afc7dcc7d4233e1d7c9c05de8cc4cd5c7166615bd2ae02d527d9d4a3c4053b3b",
          "sha256": "3ee9b2c4760728fcfd9dc9fddca28912ab6d05ed2fa7b81cfdee39ad114103c9",
          "sha1": "0bf031b93b0ac2d40d2ad9a8045375e8e3e62fc2",
          "md5": "e4cbab837d5eecd1a8c574980a51e31d"
        }
      ]
    }
  ]
}
