{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nookure.core",
    "module": "NookCore-Messenger",
    "version": "1.0.0-2df28f8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nookure.core",
          "module": "NookCore-Core",
          "version": {
            "requires": "1.0.0-2df28f8"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Event",
          "version": {
            "requires": "1.0.0-2df28f8"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Player",
          "version": {
            "requires": "1.0.0-2df28f8"
          }
        }
      ],
      "files": [
        {
          "name": "NookCore-Messenger-1.0.0-2df28f8.jar",
          "url": "NookCore-Messenger-1.0.0-2df28f8.jar",
          "size": 2300,
          "sha512": "0ad1109a84e90be11b4f0f03e42927932c6229df752a688fa5b694caaddb1febd405283de9b92874d63d625f52ddf86339da1599ee4775181d52247280c39dba",
          "sha256": "24187e08f029ed4ea76bad858f86861ded635ce666632aff8fe0227ab56a3464",
          "sha1": "1b0c4b677f50028069af06ab477261a3011833a2",
          "md5": "fde383c5dc5d19cecc48ffb0114ff021"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nookure.core",
          "module": "NookCore-Core",
          "version": {
            "requires": "1.0.0-2df28f8"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Event",
          "version": {
            "requires": "1.0.0-2df28f8"
          }
        },
        {
          "group": "com.nookure.core",
          "module": "NookCore-Player",
          "version": {
            "requires": "1.0.0-2df28f8"
          }
        }
      ],
      "files": [
        {
          "name": "NookCore-Messenger-1.0.0-2df28f8.jar",
          "url": "NookCore-Messenger-1.0.0-2df28f8.jar",
          "size": 2300,
          "sha512": "0ad1109a84e90be11b4f0f03e42927932c6229df752a688fa5b694caaddb1febd405283de9b92874d63d625f52ddf86339da1599ee4775181d52247280c39dba",
          "sha256": "24187e08f029ed4ea76bad858f86861ded635ce666632aff8fe0227ab56a3464",
          "sha1": "1b0c4b677f50028069af06ab477261a3011833a2",
          "md5": "fde383c5dc5d19cecc48ffb0114ff021"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Messenger-1.0.0-2df28f8-all.jar",
          "url": "NookCore-Messenger-1.0.0-2df28f8-all.jar",
          "size": 19144,
          "sha512": "f68a88ce9661b910339c3e117a7759d4bb881e5c53f802917247736ee6f013564a1b28beba47ffcc2ab0cd64a807fa1a6e83a16101b2b87174d5452b376016fb",
          "sha256": "dd0371c4baed039db22ee88176aebae5fce587497332779274c92290b96ec31b",
          "sha1": "bf9658606282d9f682aaf65ef1d368478e6eed87",
          "md5": "f7e7b9ae79be78fe3d7493f7bf1b4b52"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Messenger-1.0.0-2df28f8-javadoc.jar",
          "url": "NookCore-Messenger-1.0.0-2df28f8-javadoc.jar",
          "size": 82184,
          "sha512": "cb90480d6e8bee758312493ede01d5195eec7356491ad323ad2724e098dab25213e137e1a35df616f4c9787a5df7f2905c1783f6ab2a3cf930c14a11de278885",
          "sha256": "995dbc2ae73551af13e1f60a22318a7e0980f4bae21a255dfcf65cb8aab6cffe",
          "sha1": "cfe1018494d6ecca3e48e2816be81c6781630760",
          "md5": "8fb7e1091621ed3258ddd86582cbd600"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NookCore-Messenger-1.0.0-2df28f8-sources.jar",
          "url": "NookCore-Messenger-1.0.0-2df28f8-sources.jar",
          "size": 1575,
          "sha512": "0fb535e6d235b8e98dacd712152c074ccbb68f633fb9915e3dde2f2ac2738fefe10c917374caf23fd0f470483b9b168667e4e6fcade07461b21f6f2760bb6c31",
          "sha256": "4c31bf92757917d1a9a61e510a79ed7f6f4ad859f730cbd353d49edffea8f28f",
          "sha1": "f4bca90808d9f200739fe9369564d40bf9d8e3bc",
          "md5": "ea57b7b20ac111db4aea9206f2cae752"
        }
      ]
    }
  ]
}
